export const prefix = [
  {
    key: "system-mng",
    prefix: ["sys"],
    value: [
      "sysUser",
      "sysRole",
      "sysMenu",
      "sysDic",
      "organization",
      "logRecord",
      "publicNotice",
      "logRecord",
      "sysDicConfig",
      "staff",
      "dept",
      "platform",
      "resourceAccessLog",
      "resourceManager"
    ],
  },
  {
    key: "basic-datas",
    value: [
      "mtBomInfo",
      "mtBomGroup",
      "cmCustomerInfo",
      "cmCustomerGroup",
      "mtMaterialInfo",
      "mtMaterialGroup",
      "cmSupplierInfo",
      "cmSupplierGroup",
      "eqEquipment",
      "eqEquipmentType",
      "gzBasket",
      "gzBoat",
      "tnWorkingProcedure",
      "sysConfigParam",
      "mtMaterialInRecord",
      "mtMaterialInfo",
      "mtMaterialOutRecord",
      "mtMaterialInfo",
      "mtStorehouse",
      "cmCoderInfo",
    ],
  },
  {
    key: "Fixtures",
    value: ["gzBasket"],
  },
  {
    key: "produce",
    value: [
      "proProductionUnit",
      "proProductionTaskOrder",
      "proProductionLine",
      "wit",
      "wip",
      "proWorkReport",
      "queryWorkProcedureWip",
      "proProductionOrder",
      "proCallWaferMaterial",
      "proChangeShifts",
      "proChangeShiftsDetail",
      "proShiftsModel",
      "proWorkGroup",
      "proWorkSegment",
      "proWorkShift",
      "proWorkShiftPlan",
      "proWorkshop",
    ],
  },
  {
    key: "technology-manager",
    value: [
      "routeType",
      "recipe",
      "recipeVerDetail",
      "equipRecipe",
      "equipRecipeVerDetail",
      "equipRecipeVer",
      "routeInfo",
      "recipeVer",
      "tnRouteInfo",
      "recipeDetail",
      "equipRecipeCheckMonitor",
      "equipRecipeCheck",
      "tnEquipRecipeCheckDetail",
      "checkProgram",
      "checkProgramHistory",
      "equipRecipeModifyHistory",
      "equipRecipeSwitchHistory",
      "equipRecipeModifyHistoryDetail",
      "checkProgramEquip",
      "findApprovalHistoryPage",
    ],
  },
  {
    key: "reports",
    value: [
      "proKsrTar",
      "proReportsTarget",
      "capacity",
      "comprehensiveLine",
      "ELMissedDetectionReport",
      "appearanceMissedDetectionReport",
      "overkill",
      "qualitySetting",
      "overMissInspect",
      "repOeeCtSource",
      "repOeeEqException",
      "eqEquipmentReport",
      "momTensionMeter",
      "momAdhesionBoiled",
      "qualityReport",
      "momLidCidPid",
      "dayReport",
      "screenLife",
      "equipmentReport",
      "firstPassYield",
      "equipmentMaintenanceCost",
    ],
  },
  {
    key: "quality-monitor",
    value: [
      "inspectItem",
      "samplingScheme",
      "samplingSchemeItem",
      "qualityReport",
      "quality",
      "qualityPlan",
      "holdSheet",
      "qualityPlanTask",
    ],
  },
  {
    key: "andon",
    value: [
      "event",
      "eventGroup",
      "eventNoticeGroup",
      "eventRecord",
      "eventRecordProcess",
      "eventNoticeRecord",
      "kanBan",
      "softAndonKeyConfig",
    ],
  },

  {
    key: "message",
    value: ["notifier", "notifierRecord"],
  },
  {
    key: "material",
    value: ["auxiliary", "auxiliaryInstance", "auxiliaryRecord"],
  },
  {
    key: "eap",
    value: ["model"],
  },
  {
    key: "equipment-manager",
    value: [
      "equipmentMonitor",
      "warningType",
      "warningBase",
      "warning",
      "momTensionMeter",
      "momAdhesionBoiled",
      "qualityReport",
      "momLidCidPid",
      "dayReport",
      "screenLife",
    ],
  },
];
